---
title: "Show Me Perseus"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
    social: menu
    source: "https://github.com/seabbs/ShowMePerseus"
    navbar:
      - { title: "By Sam Abbott, ", href: "https://samabbott.co.uk", align: right }
      - { title: "Powered by rperseus", href: "https://ropensci.github.io/rperseus/index.html", align: right }    
runtime:  shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(DT)
library(xml2)
library(rperseus)
```

```{r global, include=FALSE}
source("utils.R")
```

Explore a Passage
==================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r inputs}
selectInput("author", 
             "Author:",
            c("-", unique(perseus_catalog$group_name)),
            selected = "-"
          )
conditionalPanel(condition = "input.author != '-'",
                uiOutput("text_ui")
                  )
conditionalPanel(condition = "input.text != '-'",
                uiOutput("language_ui")
                  )
conditionalPanel(condition = "input.language != '-'",
                uiOutput("description_ui")
                  )
conditionalPanel(condition = "input.description != '-'",
                uiOutput("excerpt_ui")
                  )
```

Row {.tabset}
-----------------------------------------------------------------------

```{r reactive-inputs}
  output$text_ui <- renderUI({
    selectInput(inputId = 'text', 
                label = 'Text:',
                c("-", perseus_catalog %>% 
                    filter(group_name %in% input$author) %>% 
                    pull(label) %>% 
                    unique),
                selected = "-")
    })

  output$language_ui <- renderUI({
    selectInput(inputId = 'language', 
                label = 'Language:',
                c("-", perseus_catalog %>% 
                    filter(group_name %in% input$author,
                           label %in% input$text) %>% 
                    pull(language) %>% 
                    unique),
                selected = "-")
    })
  
  output$description_ui <- renderUI({
    selectInput(inputId = 'description', 
                label = 'Description:',
                c("-", perseus_catalog %>% 
                    filter(group_name %in% input$author,
                           label %in% input$text,
                           language %in% input$language) %>% 
                    pull(description) %>% 
                    unique),
                selected = "-")
    })
``` 

```{r get-urn}
urn <- reactive(
  urn <- perseus_catalog %>% 
  filter(group_name == input$author,
         label == input$text,
         language == input$language,
         description == input$description) %>% 
  pull(urn) 
)
```

```{r get-all-text}
text_all <- reactive({
    text <- get_perseus_text(urn = urn(), excerpt = NULL) %>% 
      select(text, section)
})

```

```{r reactive-excerpt}
  output$excerpt_ui <- renderUI({
    
    excerpt_opts <- text_all() %>% 
                    pull(section) %>% 
      as.list
    
    selectInput(inputId = 'excerpt', 
                label = 'Excerpt:',
                choices = excerpt_opts,
                multiple = TRUE)
    })
```

### Passage 

```{r get-text}
text <- reactive(
  text_all() %>% 
    filter(section %in% input$excerpt)
)

```


```{r passage}
DT::renderDataTable({
  text()
},
      options = list(
      pageLength = 5,
      scrollX = TRUE,
      scrollY = TRUE,
      orderClasses = TRUE,
      rownames = FALSE)
)

```


### Parsed Grammer Table

```{r grammer-tab}
DT::renderDataTable({
  purrr::map_dfr(input$excerpt, function(x) {
    x <- as.character(x)
    
    if (!grepl("\\.", x)) {
          excerpt <- paste0("1.", x) 
    }
    parse_excerpt(urn(), excerpt = x)})
},
      options = list(
      pageLength = 5,
      scrollX = TRUE,
      scrollY = TRUE,
      orderClasses = TRUE,
      rownames = FALSE)
)
```


Render Parallels
==================================================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r parallels-shiny}
 textInput("books",
           label = "Books",
           value = "Colossians, 1 Thessalonians, Romans",
           placeholder = "Colossians, 1 Thessalonians, Romans")
 textInput("parallels_excerpt",
           label = "Excerpts:",
           value = "1.4, 1.3, 8.35-8.39",
           placeholder = "1.4, 1.3, 8.35-8.39")
 selectInput("parallels_language",
             label = "Language:",
             unique(perseus_catalog$language),
             selected = "grc")

```

Column
-----------------------------------------------------------------------

### Parallels

```{r process-input}
books <- reactive(
  input$books %>% 
    str_split(", ") %>% 
    unlist
)

parallels_excerpt <- reactive(
  input$parallels_excerpt %>% 
    str_split(", ") %>% 
    unlist
)
```
```{r parallels}
renderPlot(
  tibble::tibble(label = books(),
              excerpt = parallels_excerpt()) %>%
    dplyr::left_join(perseus_catalog) %>%
    dplyr::filter(language == input$parallels_language) %>%
    dplyr::select(urn, excerpt) %>%
    as.list() %>%
    purrr::pmap_df(get_perseus_text) %>%
    perseus_parallel(words_per_row = 4)
)
```
